# Generated by Django 5.0.3 on 2024-03-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('total_area', models.FloatField()),
                ('price_per_sqft', models.FloatField()),
                ('property_type', models.CharField(choices=[('commercial', 'COMMERCIAL'), ('residential', 'RESIDENTIAL')], max_length=20)),
                ('posted_date', models.DateField(auto_now=True)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
